CREATE TABLE customers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    external_id VARCHAR(255) NOT NULL UNIQUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE purchases (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    purchase_id VARCHAR(255) NOT NULL UNIQUE,
    customer_id BIGINT NOT NULL,
    amount NUMERIC(12, 2) NOT NULL,
    purchased_at TIMESTAMP WITH TIME ZONE NOT NULL,
    refunded BOOLEAN NOT NULL DEFAULT FALSE,
    refunded_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT fk_purchases_customer
        FOREIGN KEY (customer_id) REFERENCES customers (id)
);

CREATE TABLE points_ledger (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id BIGINT NOT NULL,
    purchase_id BIGINT NOT NULL,
    entry_type VARCHAR(32) NOT NULL,
    points INTEGER NOT NULL,
    remaining_points INTEGER NOT NULL,
    earned_at TIMESTAMP WITH TIME ZONE NOT NULL,
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_points_ledger_customer
        FOREIGN KEY (customer_id) REFERENCES customers (id),
    CONSTRAINT fk_points_ledger_purchase
        FOREIGN KEY (purchase_id) REFERENCES purchases (id),
    CONSTRAINT chk_points_ledger_entry_type
        CHECK (entry_type IN ('EARN', 'REFUND'))
);

CREATE TABLE refunds (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    purchase_id BIGINT NOT NULL,
    customer_id BIGINT NOT NULL,
    earned_points INTEGER NOT NULL,
    removed_available_points INTEGER NOT NULL,
    debt_points INTEGER NOT NULL,
    refunded_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_refunds_purchase
        FOREIGN KEY (purchase_id) REFERENCES purchases (id),
    CONSTRAINT fk_refunds_customer
        FOREIGN KEY (customer_id) REFERENCES customers (id)
);

CREATE INDEX idx_customers_external_id
    ON customers (external_id);

CREATE INDEX idx_purchases_customer_refunded_purchased_at
    ON purchases (customer_id, refunded, purchased_at);

CREATE INDEX idx_points_ledger_customer_expires_earned_id
    ON points_ledger (customer_id, expires_at, earned_at, id);

CREATE INDEX idx_points_ledger_purchase
    ON points_ledger (purchase_id);

CREATE INDEX idx_refunds_purchase
    ON refunds (purchase_id);

CREATE INDEX idx_refunds_customer_refunded_at
    ON refunds (customer_id, refunded_at);
